# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import daq_data_pb2 as daq__data__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in daq_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DaqDataStub(object):
    """The DaqData service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CaptureScience = channel.unary_stream(
                '/daqdata.DaqData/CaptureScience',
                request_serializer=daq__data__pb2.CaptureScienceRequest.SerializeToString,
                response_deserializer=daq__data__pb2.CaptureScienceResponse.FromString,
                _registered_method=True)


class DaqDataServicer(object):
    """The DaqData service definition.
    """

    def CaptureScience(self, request, context):
        """Stream science data from a module.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaqDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CaptureScience': grpc.unary_stream_rpc_method_handler(
                    servicer.CaptureScience,
                    request_deserializer=daq__data__pb2.CaptureScienceRequest.FromString,
                    response_serializer=daq__data__pb2.CaptureScienceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'daqdata.DaqData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('daqdata.DaqData', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DaqData(object):
    """The DaqData service definition.
    """

    @staticmethod
    def CaptureScience(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daqdata.DaqData/CaptureScience',
            daq__data__pb2.CaptureScienceRequest.SerializeToString,
            daq__data__pb2.CaptureScienceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
