# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import daq_data_pb2 as daq__data__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in daq_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DaqDataStub(object):
    """The DaqData service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CaptureScience = channel.unary_stream(
                '/daqdata.DaqData/CaptureScience',
                request_serializer=daq__data__pb2.CaptureScienceRequest.SerializeToString,
                response_deserializer=daq__data__pb2.CaptureScienceResponse.FromString,
                _registered_method=True)
        self.SetConfiguration = channel.unary_unary(
                '/daqdata.DaqData/SetConfiguration',
                request_serializer=daq__data__pb2.SetConfigurationRequest.SerializeToString,
                response_deserializer=daq__data__pb2.SetConfigurationResponse.FromString,
                _registered_method=True)
        self.UploadHashpipeImages = channel.unary_stream(
                '/daqdata.DaqData/UploadHashpipeImages',
                request_serializer=daq__data__pb2.UploadHashpipeImagesRequest.SerializeToString,
                response_deserializer=daq__data__pb2.UploadHashpipeImagesResponse.FromString,
                _registered_method=True)
        self.UploadHashpipeStatus = channel.stream_stream(
                '/daqdata.DaqData/UploadHashpipeStatus',
                request_serializer=daq__data__pb2.UploadHashpipeStatusRequest.SerializeToString,
                response_deserializer=daq__data__pb2.UploadHashpipeStatusResponse.FromString,
                _registered_method=True)


class DaqDataServicer(object):
    """The DaqData service definition.
    """

    def CaptureScience(self, request, context):
        """Stream science data [movie images | pulse-height images] from a module.
        [reader: acquires server_state lock in shared state]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfiguration(self, request, context):
        """Set the server's configuration attributes.
        Enables re-configuration without service restart.
        [writer: acquires server_state lock in exclusive state]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadHashpipeImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadHashpipeStatus(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaqDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CaptureScience': grpc.unary_stream_rpc_method_handler(
                    servicer.CaptureScience,
                    request_deserializer=daq__data__pb2.CaptureScienceRequest.FromString,
                    response_serializer=daq__data__pb2.CaptureScienceResponse.SerializeToString,
            ),
            'SetConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfiguration,
                    request_deserializer=daq__data__pb2.SetConfigurationRequest.FromString,
                    response_serializer=daq__data__pb2.SetConfigurationResponse.SerializeToString,
            ),
            'UploadHashpipeImages': grpc.unary_stream_rpc_method_handler(
                    servicer.UploadHashpipeImages,
                    request_deserializer=daq__data__pb2.UploadHashpipeImagesRequest.FromString,
                    response_serializer=daq__data__pb2.UploadHashpipeImagesResponse.SerializeToString,
            ),
            'UploadHashpipeStatus': grpc.stream_stream_rpc_method_handler(
                    servicer.UploadHashpipeStatus,
                    request_deserializer=daq__data__pb2.UploadHashpipeStatusRequest.FromString,
                    response_serializer=daq__data__pb2.UploadHashpipeStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'daqdata.DaqData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('daqdata.DaqData', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DaqData(object):
    """The DaqData service definition.
    """

    @staticmethod
    def CaptureScience(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daqdata.DaqData/CaptureScience',
            daq__data__pb2.CaptureScienceRequest.SerializeToString,
            daq__data__pb2.CaptureScienceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daqdata.DaqData/SetConfiguration',
            daq__data__pb2.SetConfigurationRequest.SerializeToString,
            daq__data__pb2.SetConfigurationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadHashpipeImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daqdata.DaqData/UploadHashpipeImages',
            daq__data__pb2.UploadHashpipeImagesRequest.SerializeToString,
            daq__data__pb2.UploadHashpipeImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadHashpipeStatus(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/daqdata.DaqData/UploadHashpipeStatus',
            daq__data__pb2.UploadHashpipeStatusRequest.SerializeToString,
            daq__data__pb2.UploadHashpipeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
