# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import daq_data_pb2 as daq__data__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in daq_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DaqDataStub(object):
    """The DaqData service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamImages = channel.unary_stream(
                '/daqdata.DaqData/StreamImages',
                request_serializer=daq__data__pb2.StreamImagesRequest.SerializeToString,
                response_deserializer=daq__data__pb2.StreamImagesResponse.FromString,
                _registered_method=True)
        self.StreamHashpipeStatus = channel.unary_stream(
                '/daqdata.DaqData/StreamHashpipeStatus',
                request_serializer=daq__data__pb2.StreamHashpipeStatusRequest.SerializeToString,
                response_deserializer=daq__data__pb2.StreamHashpipeStatusResponse.FromString,
                _registered_method=True)
        self.SetConfiguration = channel.unary_unary(
                '/daqdata.DaqData/SetConfiguration',
                request_serializer=daq__data__pb2.SetConfigurationRequest.SerializeToString,
                response_deserializer=daq__data__pb2.SetConfigurationResponse.FromString,
                _registered_method=True)
        self.InitHpIo = channel.unary_unary(
                '/daqdata.DaqData/InitHpIo',
                request_serializer=daq__data__pb2.InitHpIoRequest.SerializeToString,
                response_deserializer=daq__data__pb2.InitHpIoResponse.FromString,
                _registered_method=True)


class DaqDataServicer(object):
    """The DaqData service definition.
    """

    def StreamImages(self, request, context):
        """Stream science data [movie images | pulse-height images] from hashpipe.
        [reader: acquires server_state lock in shared state]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamHashpipeStatus(self, request, context):
        """Stream hashpipe status buffer information from hashpipe. TODO: implement this
        [reader: acquires server_state lock in shared state]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfiguration(self, request, context):
        """Set the server's configuration attributes.
        Enables re-configuration without service restart.
        [writer: acquires server_state lock in exclusive state]
        TODO: implement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitHpIo(self, request, context):
        """Initialize (or re-initialize) the hp_io thread.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaqDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamImages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamImages,
                    request_deserializer=daq__data__pb2.StreamImagesRequest.FromString,
                    response_serializer=daq__data__pb2.StreamImagesResponse.SerializeToString,
            ),
            'StreamHashpipeStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamHashpipeStatus,
                    request_deserializer=daq__data__pb2.StreamHashpipeStatusRequest.FromString,
                    response_serializer=daq__data__pb2.StreamHashpipeStatusResponse.SerializeToString,
            ),
            'SetConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfiguration,
                    request_deserializer=daq__data__pb2.SetConfigurationRequest.FromString,
                    response_serializer=daq__data__pb2.SetConfigurationResponse.SerializeToString,
            ),
            'InitHpIo': grpc.unary_unary_rpc_method_handler(
                    servicer.InitHpIo,
                    request_deserializer=daq__data__pb2.InitHpIoRequest.FromString,
                    response_serializer=daq__data__pb2.InitHpIoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'daqdata.DaqData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('daqdata.DaqData', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DaqData(object):
    """The DaqData service definition.
    """

    @staticmethod
    def StreamImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daqdata.DaqData/StreamImages',
            daq__data__pb2.StreamImagesRequest.SerializeToString,
            daq__data__pb2.StreamImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamHashpipeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daqdata.DaqData/StreamHashpipeStatus',
            daq__data__pb2.StreamHashpipeStatusRequest.SerializeToString,
            daq__data__pb2.StreamHashpipeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daqdata.DaqData/SetConfiguration',
            daq__data__pb2.SetConfigurationRequest.SerializeToString,
            daq__data__pb2.SetConfigurationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitHpIo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daqdata.DaqData/InitHpIo',
            daq__data__pb2.InitHpIoRequest.SerializeToString,
            daq__data__pb2.InitHpIoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
