# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: daq_data.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'daq_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61q_data.proto\x12\x07\x64\x61qdata\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n\x05Image\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x17\n\x0bimage_array\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x17\n\x0f\x62ytes_per_pixel\x18\x03 \x01(\x05\x12\x13\n\x0bimage_shape\x18\x04 \x03(\x05\"\xac\x02\n\x16\x43\x61ptureScienceResponse\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.daqdata.CaptureScienceResponse.Type\x12\x0c\n\x04name\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x04 \x01(\t\x12$\n\nmovie_mode\x18\x05 \x01(\x0b\x32\x0e.daqdata.ImageH\x00\x12&\n\x0cpulse_height\x18\x06 \x01(\x0b\x32\x0e.daqdata.ImageH\x00\":\n\x04Type\x12\r\n\tUNDEFINED\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x0b\n\x07\x44\x41TA_PH\x10\x02\x12\x0b\n\x07\x44\x41TA_MM\x10\x03\x42\x06\n\x04\x64\x61ta\"@\n\x15\x43\x61ptureScienceRequest\x12\'\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2`\n\x07\x44\x61qData\x12U\n\x0e\x43\x61ptureScience\x12\x1e.daqdata.CaptureScienceRequest\x1a\x1f.daqdata.CaptureScienceResponse\"\x00\x30\x01\x42)\n\x10io.grpc.daq_dataB\x0c\x44\x61qDataProtoP\x01\xa2\x02\x04\x44\x41QDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'daq_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020io.grpc.daq_dataB\014DaqDataProtoP\001\242\002\004DAQD'
  _globals['_IMAGE'].fields_by_name['image_array']._loaded_options = None
  _globals['_IMAGE'].fields_by_name['image_array']._serialized_options = b'\020\001'
  _globals['_IMAGE']._serialized_start=90
  _globals['_IMAGE']._serialized_end=209
  _globals['_CAPTURESCIENCERESPONSE']._serialized_start=212
  _globals['_CAPTURESCIENCERESPONSE']._serialized_end=512
  _globals['_CAPTURESCIENCERESPONSE_TYPE']._serialized_start=446
  _globals['_CAPTURESCIENCERESPONSE_TYPE']._serialized_end=504
  _globals['_CAPTURESCIENCEREQUEST']._serialized_start=514
  _globals['_CAPTURESCIENCEREQUEST']._serialized_end=578
  _globals['_DAQDATA']._serialized_start=580
  _globals['_DAQDATA']._serialized_end=676
# @@protoc_insertion_point(module_scope)
