# Each site block = name, host, user, password, port
# Comment out any site you don?t want to use with "#"

Gattini, panoseti-gattini, panoseti, panoseti, 5922
Winter,  panoseti-winter,  panoseti, panoseti, 5922
Fern,    panoseti-fern,    panoseti, panoseti, 5922
PTI,     panoseti-pti,     panoseti, panoseti, 5922

