# Each site block = name, host, user, password, port
# Comment out any site you don?t want to use with "#"

Gattini, panoseti-gattini, stellarmate, panoseti, 5922
#Winter,  panoseti-winter,  stellarmate, panoseti, 5922
#Fern,    panoseti-fern,    stellarmate, panoseti, 5922
#PTI,     panoseti-pti,     stellarmate, panoseti, 5922

