syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.daq_data";
option java_outer_classname = "DaqDataProto";
option objc_class_prefix = "DAQD";

package daqdata;

import "google/protobuf/struct.proto"; // standard type for JSON data structures
import "google/protobuf/timestamp.proto"; // standard type for JSON data structures

// The DaqData service definition.
service DaqData {
  // Stream science data [movie images | pulse-height images] from hashpipe.
  // [reader: acquires server_state lock in shared state]
  rpc StreamImages(StreamImagesRequest) returns (stream StreamImagesResponse) {}

  // Stream  data [movie images | pulse-height images] from a module.
  // [reader: acquires server_state lock in shared state]
  rpc StreamHashpipeStatus(StreamHashpipeStatusRequest) returns (stream StreamHashpipeStatusResponse) {}

  // Set the server's configuration attributes.
  // Enables re-configuration without service restart.
  // [writer: acquires server_state lock in exclusive state]
  rpc SetConfiguration(SetConfigurationRequest) returns (SetConfigurationResponse) {}
}

// Image represents a panoseti movie-mode or pulse-height image and associated header metadata
message PanoImage {
  enum Type {
    UNDEFINED = 0;
    PULSE_HEIGHT = 1;
    MOVIE = 2;
  }
  Type type = 1;
  // image metadata struct
  google.protobuf.Struct header = 2;
  // array of 1-byte or 2-byte data.
  repeated int32 image_array = 3 [packed=true]; // protobufs have variable sized ints, so we can use int32 for both cases.
  // image shape. Expect this field to be a list of two ints like [16, 16] or [32, 32]
  repeated int32 image_shape = 4;
  int32 bytes_per_pixel = 5;
}

// StreamImagesResponse contains one PanoImage which may be movie or pulse-height
message StreamImagesResponse {
  string name = 1;
  // UTC timestamp when this message was sent from the DAQ node
  google.protobuf.Timestamp timestamp = 2;
  // optional message for errors and other details
  string message = 3;
  // a panoseti image + self-describing metadata
  PanoImage pano_image = 4;
}

// A StreamImagesRequest specifies which image types to stream.
message StreamImagesRequest {
  // Stream movie-mode panoseti images iff True
  bool stream_movie_data = 1;
  // Stream pulse-height panoseti images iff True
  bool stream_pulse_height_data = 2;
  // Time in seconds between StreamImagesResponse packets.
  // Defaults to 1 second.
  // Notes:
  //  - For efficiency, update_interval_seconds is rounded up to the nearest integer multiple of the
  //    update_interval of the hashpipe gRPC client thread.
  double update_interval_seconds = 3;
}

message TestCase {
  enum TestResult {
    // default state
    UNDEFINED = 0;
    // the test passed
    PASS = 1;
    // the test failed
    FAIL = 2;
  }
  // test name
  string name = 1;
  // test result
  TestResult result = 2;
  // error message
  string message = 3;
}


message StreamHashpipeStatusRequest {

}

message StreamHashpipeStatusResponse {}

// TODO: implement these messages.
message SetConfigurationRequest {}
message SetConfigurationResponse {}

