syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.daq_data";
option java_outer_classname = "DaqDataProto";
option objc_class_prefix = "DAQD";

package daqdata;

import "google/protobuf/struct.proto"; // standard type for JSON data structures
import "google/protobuf/timestamp.proto"; // standard type for JSON data structures

// The DaqData service definition.
service DaqData {
  // Stream science data from a module.
  rpc CaptureScience(CaptureScienceRequest) returns (stream CaptureScienceResponse) {}
  // Configure hp_io thread. TODO: figure out the rpc interface and implement it
  rpc InitHpIo(InitHpIoRequest) returns (InitHpIoResponse) {}
}

// Image represents a panoseti movie-mode or pulse-height image and associated header metadata
message PanoImage {
  enum Type {
    UNDEFINED = 0;
    PULSE_HEIGHT = 1;
    MOVIE = 2;
  }
  Type type = 1;
  // image metadata struct
  google.protobuf.Struct header = 2;
  // array of 1-byte or 2-byte data.
  repeated int32 image_array = 3 [packed=true]; // protobufs have variable sized ints, so we can use int32 for both cases.
  // image shape. Expect this field to be a list of two ints like [16, 16] or [32, 32]
  repeated int32 image_shape = 4;
  int32 bytes_per_pixel = 5;
}

// science data packet
message CaptureScienceResponse {
  enum Type {
    UNDEFINED = 0;
    ERROR = 1;
    DATA = 2;
  }
  Type type = 1;
  string name = 2;
  // UTC timestamp when this message was sent from the DAQ node
  google.protobuf.Timestamp timestamp = 3;
  // optional message for errors and other details
  string message = 4;
  // a panoseti image + self-describing metadata
  PanoImage pano_image = 5;
}

// A CaptureScienceRequest specifies which image types to stream.
message CaptureScienceRequest {
  bool stream_movie_data = 1;
  bool stream_pulse_height_data = 2;
  google.protobuf.Struct config = 3;
}

message TestCase {
  enum TestResult {
    // default state
    UNDEFINED = 0;
    // the test passed
    PASS = 1;
    // the test failed
    FAIL = 2;
  }
  // test name
  string name = 1;
  // test result
  TestResult result = 2;
  // error message
  string message = 3;
}

message InitHpIoRequest {}
message InitHpIoResponse {}

