# name,ssh_user,ssh_host,ssh_port,indi_port,device
#Gattini,panoseti,panoseti-gattini,5922,7624,"iOptron HAE69"
Winter,panoseti,panoseti-winter,5922,7624,"iOptron HAE69"
Fern,panoseti,panoseti-fern,5922,7624,"iOptron HAE69"
PTI,panoseti,panoseti-pti,5922,7624,"iOptron HAE69"

