# site_name, ip, username, password
Gattini,10.200.146.11,admin,epowerpanoseti
Winter,10.200.146.12,panoseti,epowerpanoseti
Fern,10.200.146.13,panoseti,epowerpanoseti
PTI,10.200.146.14,panoseti,epowerpanoseti

